services:
  # Backend (FastAPI)
  - type: web
    name: multi-agent-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: BACKEND_URL
        value: https://multi-agent-backend.onrender.com
    autoDeploy: true

  # Frontend (Streamlit)
  - type: web
    name: multi-agent-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    envVars:
      - key: BACKEND_URL
        value: https://multi-agent-backend.onrender.com
    autoDeploy: true
