services:
  - type: web
    name: nebula-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false

  - type: web
    name: nebula-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        fromService:
          name: nebula-backend
          type: web
